[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
casino_bank = "99xm6t1bmVaQQe3nH6QTEkRh5mqQnQtCh6jUMqnXuyMe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/tulip/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
